version: '3'

# docker rm $(docker ps -a -q) && docker volume prune -f

services:
  mysql:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "love"
      MYSQL_DATABASE: golang
    ports:
      - '3307:3306'
    volumes:
      - './_mysql/:/docker-entrypoint-initdb.d/'